services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      sh -c "
        while ! nc -z db 5432; do sleep 1; done &&
        if [ ! -f /app/migrations/versions/*.py ]; then
          alembic revision --autogenerate -m 'initial' &&
          alembic upgrade head;
        else
          alembic upgrade head;
        fi &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "5000:5000"
  db:
    image: postgres:13
    container_name: postgres-db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
